name: Laravel_prod

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.production', '.env');"
      - name: Touch database
        run: touch database/database.sqlite3
      - name: Install Dependencies with composer
        run: composer install
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Generate key
        run: php artisan key:generate
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies with npm
        run: npm ci
      - name: Build with npm
        run: npm run prod
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite3
        run: vendor/bin/phpunit
